name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23.x'
      - uses: hashicorp/setup-terraform@v4
      - run: make lint
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23.x'
      - uses: hashicorp/setup-terraform@v4
      - name: Generate docs automatically
        run: make gen
      - name: Check no versioned file has been updated
        run: git add -A && git diff --cached --exit-code
