name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: hashicorp/setup-terraform@v3
      - run: make lint
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: hashicorp/setup-terraform@v3
      - name: Generate docs automatically
        run: make gen
      - name: Check no versioned file has been updated
        uses: numtide/clean-git-action@v1
